version: "3.8"
services:
  api:
    build: .
    container_name: api_file_storage
    hostname: api
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
